var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/patient/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgk94w._.js")
R.c("server/chunks/ssr/node_modules_09r9c10._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_19wksra.js")
R.c("server/chunks/ssr/[root-of-the-server]__09fvjsw._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__17y6r1f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_patient_page_actions_0s1j2ec.js")
R.m(36705)
module.exports=R.m(36705).exports
