var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/settings/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0vq79uv._.js")
R.c("server/chunks/ssr/node_modules_09r9c10._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_217kfsw.js")
R.c("server/chunks/ssr/[root-of-the-server]__09fvjsw._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__17y6r1f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_app_settings_loading_tsx_1wj_uuv._.js")
R.c("server/chunks/ssr/_next-internal_server_app_settings_page_actions_11x4dq5.js")
R.m(63524)
module.exports=R.m(63524).exports
