/**
 * CareConnect Event Schema (Constants)
 * Defines all system-wide events for event-driven orchestration.
 * In a scale architecture, these map to Kafka Topics.
 */

module.exports = {
    // 🔴 CRITICAL & EMERGENCY EVENTS
    EMERGENCY_TRIGGERED: 'EMERGENCY_TRIGGERED', // Manual SOS or critical AI detection
    AMBULANCE_DISPATCHED: 'AMBULANCE_DISPATCHED',
    HOSPITAL_ALERTED: 'HOSPITAL_ALERTED',
    EMERGENCY_RESOLVED: 'EMERGENCY_RESOLVED',

    // 🧠 AI ENGINE EVENTS
    AI_SYMPTOM_EVALUATED: 'AI_SYMPTOM_EVALUATED',
    AI_RISK_ESCALATED: 'AI_RISK_ESCALATED', // E.g., Low -> Medium risk over time
    AI_SCAN_ANALYZED: 'AI_SCAN_ANALYZED',
    AI_LEARNING_DATA_CAPTURED: 'AI_LEARNING_DATA_CAPTURED',

    // 👨‍⚕️ CLINICAL FLOW EVENTS
    DOCTOR_CONSULT_STARTED: 'DOCTOR_CONSULT_STARTED',
    DOCTOR_ORDERED_LABS: 'DOCTOR_ORDERED_LABS',
    DOCTOR_ORDERED_SCAN: 'DOCTOR_ORDERED_SCAN',
    CASE_REFERRED_TO_SPECIALIST: 'CASE_REFERRED_TO_SPECIALIST',

    // 🧪 LAB & RADIOLOGY EVENTS
    LAB_RESULTS_UPLOADED: 'LAB_RESULTS_UPLOADED',
    LAB_RESULTS_ABNORMAL: 'LAB_RESULTS_ABNORMAL', // Triggers auto-escalation
    SCAN_UPLOADED: 'SCAN_UPLOADED',
    SCAN_ASSIGNED_TO_RAD: 'SCAN_ASSIGNED_TO_RAD',
    RADIOLOGY_REPORT_FINALIZED: 'RADIOLOGY_REPORT_FINALIZED',
};
